// Generated by package.gen.ts
// Do not edit directly - regenerated on build

import type {Package_Json} from '@ryanatkn/belt/package_json.js';
import type {Src_Json} from '@ryanatkn/belt/src_json.js';

export const package_json: Package_Json = {
	name: '@ryanatkn/fuz_template',
	version: '0.0.1',
	description:
		'a static web app and Node library template with TypeScript, Svelte, SvelteKit, Vite, esbuild, Gro, and Fuz',
	glyph: '❄',
	logo: 'logo.svg',
	logo_alt: 'a friendly pixelated spider facing you',
	public: true,
	homepage: 'https://template.fuz.dev/',
	repository: 'https://github.com/ryanatkn/fuz_template',
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		check: 'gro check',
		test: 'gro test',
		preview: 'vite preview',
		deploy: 'gro deploy',
	},
	type: 'module',
	engines: {
		node: '>=22.15',
	},
	devDependencies: {
		'@ryanatkn/belt': '^0.38.0',
		'@ryanatkn/eslint-config': '^0.9.0',
		'@ryanatkn/fuz': '^0.159.0',
		'@ryanatkn/gro': '^0.174.2',
		'@ryanatkn/moss': '^0.38.0',
		'@sveltejs/adapter-static': '^3.0.10',
		'@sveltejs/kit': '^2.49.0',
		'@sveltejs/vite-plugin-svelte': '^6.2.1',
		eslint: '^9.39.1',
		'eslint-plugin-svelte': '^3.13.0',
		prettier: '^3.6.2',
		'prettier-plugin-svelte': '^3.4.0',
		svelte: '^5.43.14',
		'svelte-check': '^4.3.4',
		tslib: '^2.8.1',
		typescript: '^5.9.3',
		'typescript-eslint': '^8.47.0',
		vitest: '^4.0.13',
	},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [
			{
				files: 'package.json',
				options: {
					useTabs: false,
				},
			},
		],
	},
	sideEffects: ['**/*.css'],
	files: ['dist'],
};

export const src_json: Src_Json = {
	name: '@ryanatkn/fuz_template',
	version: '0.0.1',
	modules: [],
};
